//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ferre2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_factura
    {
        public int id_detalle { get; set; }
        public int id_factura { get; set; }
        public int id_producto { get; set; }
        public string descripcion { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal descuento_porcentaje { get; set; }
        public decimal descuento_valor { get; set; }
        public decimal iva_porcentaje { get; set; }
        public decimal iva_valor { get; set; }
        public decimal subtotal { get; set; }
        public decimal total_linea { get; set; }
    
        public virtual facturas facturas { get; set; }
        public virtual productos productos { get; set; }
    }
}
