//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ferre2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturas()
        {
            this.detalles_factura = new HashSet<detalles_factura>();
        }
    
        public int id_factura { get; set; }
        public string numero_factura { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public int id_cliente { get; set; }
        public decimal subtotal { get; set; }
        public decimal total_impuestos { get; set; }
        public decimal total_descuentos { get; set; }
        public decimal total { get; set; }
        public string estado { get; set; }
        public string metodo_pago { get; set; }
        public string notas { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_factura> detalles_factura { get; set; }
    }
}
